# Selwyn

In [1]:
library(tidyr)
library(tidyverse)
library(readr)
library(skimr)
library(readxl)
library(read_excel)
library(tidyxl)
library(hablar)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──

✔ ggplot2 3.3.2     ✔ dplyr   1.0.2
✔ tibble  3.0.3     ✔ stringr 1.4.0
✔ readr   1.3.1     ✔ forcats 0.5.0
✔ purrr   0.3.4

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

ERROR: Error in library(skimr): there is no package called ‘skimr’

In [2]:
setwd("~/Documents/Uni/DATA422/Group_Project/Pet_CSV")

In [3]:
data = read_csv("Selwyn.csv")
pets_data = data[data$Topic == "Pets",]
pets_data
pets_data$Topic = NULL
pets_data$NullReason = NULL
pets_data$Source = NULL
pets_data$ValueUnit = NULL
pets_data$ValueLabel = NULL
skim(pets_data)
pets_data

Parsed with column specification:
cols(
  `Territorial Authority` = col_character(),
  Topic = col_character(),
  Measure = col_character(),
  Category = col_character(),
  Value = col_double(),
  ValueUnit = col_character(),
  ValueLabel = col_character(),
  NullReason = col_character(),
  Date = col_character(),
  DateLabel = col_character(),
  Source = col_character()
)

    Territorial Authority Topic Measure
1   Selwyn                Pets  ACC Statistics — Dog-related injury
2   Selwyn                Pets  ACC Statistics — Dog-related injury
3   Selwyn                Pets  ACC Statistics — Dog-related injury
4   Selwyn                Pets  Registered dogs — De-sexed dogs
5   Selwyn                Pets  Registered dogs — De-sexed dogs
6   Selwyn                Pets  Registered dogs — De-sexed dogs
7   Selwyn                Pets  Registered dogs — De-sexed dogs
8   Selwyn                Pets  Registered dogs — De-sexed dogs
9   Selwyn                Pets  Registered dogs — De-sexed dogs
10  Selwyn                Pets  Registered dogs — De-sexed dogs
11  Selwyn                Pets  Registered dogs — De-sexed dogs
12  Selwyn                Pets  Registered dogs — De-sexed dogs
13  Selwyn                Pets  Registered dogs — De-sexed dogs
14  Selwyn                Pets  Registered dogs — De-sexed dogs
15  Selwyn                Pets  Registered dogs — De-sexed dogs
16  Selwyn                Pets  Registered dogs — De-sexed dogs
17  Selwyn                Pets  Registered dogs — De-sexed dogs
18  Selwyn                Pets  Registered dogs — De-sexed dogs
19  Selwyn                Pets  Registered dogs — De-sexed dogs
20  Selwyn                Pets  Registered dogs — De-sexed dogs
21  Selwyn                Pets  Registered dogs — De-sexed dogs
22  Selwyn                Pets  Registered dogs — De-sexed dogs
23  Selwyn                Pets  Registered dogs — De-sexed dogs
24  Selwyn                Pets  Registered dogs — De-sexed dogs
25  Selwyn                Pets  Registered dogs — De-sexed dogs
26  Selwyn                Pets  Registered dogs — De-sexed dogs
27  Selwyn                Pets  Registered dogs — De-sexed dogs
28  Selwyn                Pets  Registered dogs — De-sexed dogs
29  Selwyn                Pets  Registered dogs — De-sexed dogs
30  Selwyn                Pets  Registered dogs — De-sexed dogs
⋮   ⋮                     ⋮     ⋮
240 Selwyn                Pets  Registered dogs — Total registered dogs
241 Selwyn                Pets  Registered dogs — Total registered dogs
242 Selwyn                Pets  Registered dogs — Total registered dogs
243 Selwyn                Pets  Registered dogs — Total registered dogs
244 Selwyn                Pets  Registered dogs — Total registered dogs
245 Selwyn                Pets  Registered dogs — Total registered dogs
246 Selwyn                Pets  Registered dogs — Total registered dogs
247 Selwyn                Pets  Registered dogs — Total registered dogs
248 Selwyn                Pets  Registered dogs — Total registered dogs
249 Selwyn                Pets  Registered dogs — Total registered dogs
250 Selwyn                Pets  Registered dogs — Total registered dogs
251 Selwyn                Pets  Registered dogs — Total registered dogs
252 Selwyn                Pets  Registered dogs — Total registered dogs
253 Selwyn                Pets  Registered dogs — Total registered dogs
254 Selwyn                Pets  Registered dogs — Total registered dogs
255 Selwyn                Pets  Registered dogs — Total registered dogs
256 Selwyn                Pets  Registered dogs — Total registered dogs
257 Selwyn                Pets  Registered dogs — Total registered dogs
258 Selwyn                Pets  Registered dogs — Total registered dogs
259 Selwyn                Pets  Registered dogs — Total registered dogs
260 Selwyn                Pets  Registered dogs — Total registered dogs
261 Selwyn                Pets  Registered dogs — Total registered dogs
262 Selwyn                Pets  Registered dogs — Total registered dogs
263 Selwyn                Pets  Registered dogs — Total registered dogs
264 Selwyn                Pets  Registered dogs — Total registered dogs
265 Selwyn                Pets  Registered dogs — Total registered dogs
266 Selwyn                Pets  Registered dogs — Total registered dogs
267 Selwyn                Pets  Registered dogs — Total registered dogs
268 Selwyn                Pets  Registered dogs — Total registered dogs
269 Selwyn                Pets  Registered dogs — Total registered dogs
    Category
1   New claims
2   Cost of claims for dog-related injuries received in year (excl. GST)
3   Total cost of claims for all dog-related injuries ever received, up until date (excl. GST)
4   All pure and cross breeds
5   All pure breeds
6   Beagle
7   Bichon Frise
8   Boxer
9   Brazilian Fila
10  Cattle, Australian
11  Chihuahua, Long Coat
12  Chihuahua, Smooth Coat
13  Collie, Bearded
14  Collie, Border
15  Collie, Rough
16  Collie, Smooth
17  Dogo Argentino
18  Greyhound
19  Heading
20  Huntaway
21  Maltese
22  Perro de Presa Canario
23  Poodle, Miniature
24  Poodle, Toy
25  Retriever, Golden
26  Retriever, Labrador
27  Rottweiler
28  Schnauzer, Miniature
29  Shepherd, German
30  Shih Tzu
⋮   ⋮
240 Chihuahua, Smooth Coat
241 Collie, Bearded
242 Collie, Border
243 Collie, Rough
244 Collie, Smooth
245 Dogo Argentino
246 Greyhound
247 Heading
248 Huntaway
249 Maltese
250 Perro de Presa Canario
251 Poodle, Miniature
252 Poodle, Toy
253 Retriever, Golden
254 Retriever, Labrador
255 Rottweiler
256 Schnauzer, Miniature
257 Shepherd, German
258 Shih Tzu
259 Spaniel, Cavalier King Charles
260 Spaniel, Cocker
261 Spaniel, English Springer
262 Terrier, American Pit Bull
263 Terrier, Fox (Smooth)
264 Terrier, Jack Russell
265 Terrier, Staffordshire Bull
266 Terrier, West Highland White
267 Tosa, Japanese
268 Other pure breeds
269 All cross breeds
    Value    ValueUnit ValueLabel           NullReason Date DateLabel
1      81.00 number    Number of new claims NA         2018 Year ended June
2   28302.62 nzd       NZD                  NA         2018 Year ended June
3   30307.96 nzd       NZD                  NA         2018 Year ended June
4    5215.00 number    Number of dogs       NA         2019 Year ended June
5    3192.00 number    Number of dogs       NA         2019 Year ended June
6      40.00 number    Number of dogs       NA         2019 Year ended June
7      85.00 number    Number of dogs       NA         2019 Year ended June
8      54.00 number    Number of dogs       NA         2019 Year ended June
9       0.00 number    Number of dogs       NA         2019 Year ended June
10     26.00 number    Number of dogs       NA         2019 Year ended June
11     38.00 number    Number of dogs       NA         2019 Year ended June
12     34.00 number    Number of dogs       NA         2019 Year ended June
13     26.00 number    Number of dogs       NA         2019 Year ended June
14    262.00 number    Number of dogs       NA         2019 Year ended June
15      8.00 number    Number of dogs       NA         2019 Year ended June
16     10.00 number    Number of dogs       NA         2019 Year ended June
17      0.00 number    Number of dogs       NA         2019 Year ended June
18     27.00 number    Number of dogs       NA         2019 Year ended June
19     27.00 number    Number of dogs       NA         2019 Year ended June
20     69.00 number    Number of dogs       NA         2019 Year ended June
21     39.00 number    Number of dogs       NA         2019 Year ended June
22      0.00 number    Number of dogs       NA         2019 Year ended June
23     22.00 number    Number of dogs       NA         2019 Year ended June
24     30.00 number    Number of dogs       NA         2019 Year ended June
25    125.00 number    Number of dogs       NA         2019 Year ended June
26    456.00 number    Number of dogs       NA         2019 Year ended June
27     30.00 number    Number of dogs       NA         2019 Year ended June
28     91.00 number    Number of dogs       NA         2019 Year ended June
29    114.00 number    Number of dogs       NA         2019 Year ended June
30     31.00 number    Number of dogs       NA         2019 Year ended June
⋮   ⋮        ⋮         ⋮                    ⋮          ⋮    ⋮
240   67     number    Number of dogs       NA         2019 Year ended June
241   99     number    Number of dogs       NA         2019 Year ended June
242  929     number    Number of dogs       NA         2019 Year ended June
243   27     number    Number of dogs       NA         2019 Year ended June
244   62     number    Number of dogs       NA         2019 Year ended June
245    0     number    Number of dogs       NA         2019 Year ended June
246  349     number    Number of dogs       NA         2019 Year ended June
247  327     number    Number of dogs       NA         2019 Year ended June
248  567     number    Number of dogs       NA         2019 Year ended June
249   68     number    Number of dogs       NA         2019 Year ended June
250    0     number    Number of dogs       NA         2019 Year ended June
251   72     number    Number of dogs       NA         2019 Year ended June
252   60     number    Number of dogs       NA         2019 Year ended June
253  417     number    Number of dogs       NA         2019 Year ended June
254 1175     number    Number of dogs       NA         2019 Year ended June
255  110     number    Number of dogs       NA         2019 Year ended June
256  234     number    Number of dogs       NA         2019 Year ended June
257  408     number    Number of dogs       NA         2019 Year ended June
258   78     number    Number of dogs       NA         2019 Year ended June
259   61     number    Number of dogs       NA         2019 Year ended June
260  174     number    Number of dogs       NA         2019 Year ended June
261  157     number    Number of dogs       NA         2019 Year ended June
262   14     number    Number of dogs       NA         2019 Year ended June
263  250     number    Number of dogs       NA         2019 Year ended June
264  491     number    Number of dogs       NA         2019 Year ended June
265  252     number    Number of dogs       NA         2019 Year ended June
266   87     number    Number of dogs       NA         2019 Year ended June
267    0     number    Number of dogs       NA         2019 Year ended June
268 2414     number    Number of dogs       NA         2019 Year ended June
269 4446     number    Number of dogs       NA         2019 Year ended June
    Source
1   https://figure.nz/table/fK7iZAOJhHHirYPk
2   https://figure.nz/table/fK7iZAOJhHHirYPk
3   https://figure.nz/table/fK7iZAOJhHHirYPk
4   https://figure.nz/table/fK7iZAOJhHHirYPk
5   https://figure.nz/table/fK7iZAOJhHHirYPk
6   https://figure.nz/table/fK7iZAOJhHHirYPk
7   https://figure.nz/table/fK7iZAOJhHHirYPk
8   https://figure.nz/table/fK7iZAOJhHHirYPk
9   https://figure.nz/table/fK7iZAOJhHHirYPk
10  https://figure.nz/table/fK7iZAOJhHHirYPk
11  https://figure.nz/table/fK7iZAOJhHHirYPk
12  https://figure.nz/table/fK7iZAOJhHHirYPk
13  https://figure.nz/table/fK7iZAOJhHHirYPk
14  https://figure.nz/table/fK7iZAOJhHHirYPk
15  https://figure.nz/table/fK7iZAOJhHHirYPk
16  https://figure.nz/table/fK7iZAOJhHHirYPk
17  https://figure.nz/table/fK7iZAOJhHHirYPk
18  https://figure.nz/table/fK7iZAOJhHHirYPk
19  https://figure.nz/table/fK7iZAOJhHHirYPk
20  https://figure.nz/table/fK7iZAOJhHHirYPk
21  https://figure.nz/table/fK7iZAOJhHHirYPk
22  https://figure.nz/table/fK7iZAOJhHHirYPk
23  https://figure.nz/table/fK7iZAOJhHHirYPk
24  https://figure.nz/table/fK7iZAOJhHHirYPk
25  https://figure.nz/table/fK7iZAOJhHHirYPk
26  https://figure.nz/table/fK7iZAOJhHHirYPk
27  https://figure.nz/table/fK7iZAOJhHHirYPk
28  https://figure.nz/table/fK7iZAOJhHHirYPk
29  https://figure.nz/table/fK7iZAOJhHHirYPk
30  https://figure.nz/table/fK7iZAOJhHHirYPk
⋮   ⋮
240 https://figure.nz/table/fK7iZAOJhHHirYPk
241 https://figure.nz/table/fK7iZAOJhHHirYPk
242 https://figure.nz/table/fK7iZAOJhHHirYPk
243 https://figure.nz/table/fK7iZAOJhHHirYPk
244 https://figure.nz/table/fK7iZAOJhHHirYPk
245 https://figure.nz/table/fK7iZAOJhHHirYPk
246 https://figure.nz/table/fK7iZAOJhHHirYPk
247 https://figure.nz/table/fK7iZAOJhHHirYPk
248 https://figure.nz/table/fK7iZAOJhHHirYPk
249 https://figure.nz/table/fK7iZAOJhHHirYPk
250 https://figure.nz/table/fK7iZAOJhHHirYPk
251 https://figure.nz/table/fK7iZAOJhHHirYPk
252 https://figure.nz/table/fK7iZAOJhHHirYPk
253 https://figure.nz/table/fK7iZAOJhHHirYPk
254 https://figure.nz/table/fK7iZAOJhHHirYPk
255 https://figure.nz/table/fK7iZAOJhHHirYPk
256 https://figure.nz/table/fK7iZAOJhHHirYPk
257 https://figure.nz/table/fK7iZAOJhHHirYPk
258 https://figure.nz/table/fK7iZAOJhHHirYPk
259 https://figure.nz/table/fK7iZAOJhHHirYPk
260 https://figure.nz/table/fK7iZAOJhHHirYPk
261 https://figure.nz/table/fK7iZAOJhHHirYPk
262 https://figure.nz/table/fK7iZAOJhHHirYPk
263 https://figure.nz/table/fK7iZAOJhHHirYPk
264 https://figure.nz/table/fK7iZAOJhHHirYPk
265 https://figure.nz/table/fK7iZAOJhHHirYPk
266 https://figure.nz/table/fK7iZAOJhHHirYPk
267 https://figure.nz/table/fK7iZAOJhHHirYPk
268 https://figure.nz/table/fK7iZAOJhHHirYPk
269 https://figure.nz/table/fK7iZAOJhHHirYPk

ERROR: Error in skim(pets_data): could not find function "skim"

In [4]:
#extract the rows pertaining to ACC information 
acc_pets = pets_data[1:3,]
acc_pets

  Territorial Authority Measure
1 Selwyn                ACC Statistics — Dog-related injury
2 Selwyn                ACC Statistics — Dog-related injury
3 Selwyn                ACC Statistics — Dog-related injury
  Category
1 New claims
2 Cost of claims for dog-related injuries received in year (excl. GST)
3 Total cost of claims for all dog-related injuries ever received, up until date (excl. GST)
  Value    Date DateLabel
1    81.00 2018 Year ended June
2 28302.62 2018 Year ended June
3 30307.96 2018 Year ended June

In [5]:
#Then we can extract the rows pertaining to specific counts of dogs 
pets_counts = pets_data[c(-1,-2,-3),]
pets_counts

    Territorial Authority Measure
1   Selwyn                Registered dogs — De-sexed dogs
2   Selwyn                Registered dogs — De-sexed dogs
3   Selwyn                Registered dogs — De-sexed dogs
4   Selwyn                Registered dogs — De-sexed dogs
5   Selwyn                Registered dogs — De-sexed dogs
6   Selwyn                Registered dogs — De-sexed dogs
7   Selwyn                Registered dogs — De-sexed dogs
8   Selwyn                Registered dogs — De-sexed dogs
9   Selwyn                Registered dogs — De-sexed dogs
10  Selwyn                Registered dogs — De-sexed dogs
11  Selwyn                Registered dogs — De-sexed dogs
12  Selwyn                Registered dogs — De-sexed dogs
13  Selwyn                Registered dogs — De-sexed dogs
14  Selwyn                Registered dogs — De-sexed dogs
15  Selwyn                Registered dogs — De-sexed dogs
16  Selwyn                Registered dogs — De-sexed dogs
17  Selwyn                Registered dogs — De-sexed dogs
18  Selwyn                Registered dogs — De-sexed dogs
19  Selwyn                Registered dogs — De-sexed dogs
20  Selwyn                Registered dogs — De-sexed dogs
21  Selwyn                Registered dogs — De-sexed dogs
22  Selwyn                Registered dogs — De-sexed dogs
23  Selwyn                Registered dogs — De-sexed dogs
24  Selwyn                Registered dogs — De-sexed dogs
25  Selwyn                Registered dogs — De-sexed dogs
26  Selwyn                Registered dogs — De-sexed dogs
27  Selwyn                Registered dogs — De-sexed dogs
28  Selwyn                Registered dogs — De-sexed dogs
29  Selwyn                Registered dogs — De-sexed dogs
30  Selwyn                Registered dogs — De-sexed dogs
⋮   ⋮                     ⋮
237 Selwyn                Registered dogs — Total registered dogs
238 Selwyn                Registered dogs — Total registered dogs
239 Selwyn                Registered dogs — Total registered dogs
240 Selwyn                Registered dogs — Total registered dogs
241 Selwyn                Registered dogs — Total registered dogs
242 Selwyn                Registered dogs — Total registered dogs
243 Selwyn                Registered dogs — Total registered dogs
244 Selwyn                Registered dogs — Total registered dogs
245 Selwyn                Registered dogs — Total registered dogs
246 Selwyn                Registered dogs — Total registered dogs
247 Selwyn                Registered dogs — Total registered dogs
248 Selwyn                Registered dogs — Total registered dogs
249 Selwyn                Registered dogs — Total registered dogs
250 Selwyn                Registered dogs — Total registered dogs
251 Selwyn                Registered dogs — Total registered dogs
252 Selwyn                Registered dogs — Total registered dogs
253 Selwyn                Registered dogs — Total registered dogs
254 Selwyn                Registered dogs — Total registered dogs
255 Selwyn                Registered dogs — Total registered dogs
256 Selwyn                Registered dogs — Total registered dogs
257 Selwyn                Registered dogs — Total registered dogs
258 Selwyn                Registered dogs — Total registered dogs
259 Selwyn                Registered dogs — Total registered dogs
260 Selwyn                Registered dogs — Total registered dogs
261 Selwyn                Registered dogs — Total registered dogs
262 Selwyn                Registered dogs — Total registered dogs
263 Selwyn                Registered dogs — Total registered dogs
264 Selwyn                Registered dogs — Total registered dogs
265 Selwyn                Registered dogs — Total registered dogs
266 Selwyn                Registered dogs — Total registered dogs
    Category                       Value Date DateLabel
1   All pure and cross breeds      5215  2019 Year ended June
2   All pure breeds                3192  2019 Year ended June
3   Beagle                           40  2019 Year ended June
4   Bichon Frise                     85  2019 Year ended June
5   Boxer                            54  2019 Year ended June
6   Brazilian Fila                    0  2019 Year ended June
7   Cattle, Australian               26  2019 Year ended June
8   Chihuahua, Long Coat             38  2019 Year ended June
9   Chihuahua, Smooth Coat           34  2019 Year ended June
10  Collie, Bearded                  26  2019 Year ended June
11  Collie, Border                  262  2019 Year ended June
12  Collie, Rough                     8  2019 Year ended June
13  Collie, Smooth                   10  2019 Year ended June
14  Dogo Argentino                    0  2019 Year ended June
15  Greyhound                        27  2019 Year ended June
16  Heading                          27  2019 Year ended June
17  Huntaway                         69  2019 Year ended June
18  Maltese                          39  2019 Year ended June
19  Perro de Presa Canario            0  2019 Year ended June
20  Poodle, Miniature                22  2019 Year ended June
21  Poodle, Toy                      30  2019 Year ended June
22  Retriever, Golden               125  2019 Year ended June
23  Retriever, Labrador             456  2019 Year ended June
24  Rottweiler                       30  2019 Year ended June
25  Schnauzer, Miniature             91  2019 Year ended June
26  Shepherd, German                114  2019 Year ended June
27  Shih Tzu                         31  2019 Year ended June
28  Spaniel, Cavalier King Charles   25  2019 Year ended June
29  Spaniel, Cocker                  78  2019 Year ended June
30  Spaniel, English Springer        48  2019 Year ended June
⋮   ⋮                              ⋮     ⋮    ⋮
237 Chihuahua, Smooth Coat           67  2019 Year ended June
238 Collie, Bearded                  99  2019 Year ended June
239 Collie, Border                  929  2019 Year ended June
240 Collie, Rough                    27  2019 Year ended June
241 Collie, Smooth                   62  2019 Year ended June
242 Dogo Argentino                    0  2019 Year ended June
243 Greyhound                       349  2019 Year ended June
244 Heading                         327  2019 Year ended June
245 Huntaway                        567  2019 Year ended June
246 Maltese                          68  2019 Year ended June
247 Perro de Presa Canario            0  2019 Year ended June
248 Poodle, Miniature                72  2019 Year ended June
249 Poodle, Toy                      60  2019 Year ended June
250 Retriever, Golden               417  2019 Year ended June
251 Retriever, Labrador            1175  2019 Year ended June
252 Rottweiler                      110  2019 Year ended June
253 Schnauzer, Miniature            234  2019 Year ended June
254 Shepherd, German                408  2019 Year ended June
255 Shih Tzu                         78  2019 Year ended June
256 Spaniel, Cavalier King Charles   61  2019 Year ended June
257 Spaniel, Cocker                 174  2019 Year ended June
258 Spaniel, English Springer       157  2019 Year ended June
259 Terrier, American Pit Bull       14  2019 Year ended June
260 Terrier, Fox (Smooth)           250  2019 Year ended June
261 Terrier, Jack Russell           491  2019 Year ended June
262 Terrier, Staffordshire Bull     252  2019 Year ended June
263 Terrier, West Highland White     87  2019 Year ended June
264 Tosa, Japanese                    0  2019 Year ended June
265 Other pure breeds              2414  2019 Year ended June
266 All cross breeds               4446  2019 Year ended June

In [6]:
#And we can extract rows and make tables therefore of the different measures of dogs they have 
desexed_counts = pets_counts[pets_counts$Measure == "Registered dogs — De-sexed dogs",]
desexed_counts %>%
head()

dangerous_counts = pets_counts[pets_counts$Measure =="Registered dogs — Dogs classified as dangerous",]
dangerous_counts %>%
head()

menacing_counts = pets_counts[pets_counts$Measure =="Registered dogs — Dogs classified as menacing",]
menacing_counts %>%
head()

total_registered_dogs = pets_counts[pets_counts$Measure =="Registered dogs — Total registered dogs",]
total_registered_dogs %>%
head()

male_dogs = pets_counts[pets_counts$Measure =="Registered dogs — Male dogs",]
male_dogs %>%
head()

female_dogs = pets_counts[pets_counts$Measure == "Registered dogs — Female dogs",]
female_dogs %>%
head()

microchipped_dogs = pets_counts[pets_counts$Measure =="Registered dogs — Micro-chipped dogs",]
microchipped_dogs %>%
head()

  Territorial Authority Measure
1 Selwyn                Registered dogs — De-sexed dogs
2 Selwyn                Registered dogs — De-sexed dogs
3 Selwyn                Registered dogs — De-sexed dogs
4 Selwyn                Registered dogs — De-sexed dogs
5 Selwyn                Registered dogs — De-sexed dogs
6 Selwyn                Registered dogs — De-sexed dogs
  Category                  Value Date DateLabel
1 All pure and cross breeds 5215  2019 Year ended June
2 All pure breeds           3192  2019 Year ended June
3 Beagle                      40  2019 Year ended June
4 Bichon Frise                85  2019 Year ended June
5 Boxer                       54  2019 Year ended June
6 Brazilian Fila               0  2019 Year ended June

  Territorial Authority Measure
1 Selwyn                Registered dogs — Dogs classified as dangerous
2 Selwyn                Registered dogs — Dogs classified as dangerous
3 Selwyn                Registered dogs — Dogs classified as dangerous
4 Selwyn                Registered dogs — Dogs classified as dangerous
5 Selwyn                Registered dogs — Dogs classified as dangerous
6 Selwyn                Registered dogs — Dogs classified as dangerous
  Category                  Value Date DateLabel
1 All pure and cross breeds 14    2019 Year ended June
2 All pure breeds            6    2019 Year ended June
3 Beagle                     0    2019 Year ended June
4 Bichon Frise               0    2019 Year ended June
5 Boxer                      0    2019 Year ended June
6 Brazilian Fila             0    2019 Year ended June

  Territorial Authority Measure
1 Selwyn                Registered dogs — Dogs classified as menacing
2 Selwyn                Registered dogs — Dogs classified as menacing
3 Selwyn                Registered dogs — Dogs classified as menacing
4 Selwyn                Registered dogs — Dogs classified as menacing
5 Selwyn                Registered dogs — Dogs classified as menacing
6 Selwyn                Registered dogs — Dogs classified as menacing
  Category                  Value Date DateLabel
1 All pure and cross breeds 76    2019 Year ended June
2 All pure breeds           43    2019 Year ended June
3 Beagle                     0    2019 Year ended June
4 Bichon Frise               0    2019 Year ended June
5 Boxer                      1    2019 Year ended June
6 Brazilian Fila             0    2019 Year ended June

  Territorial Authority Measure
1 Selwyn                Registered dogs — Total registered dogs
2 Selwyn                Registered dogs — Total registered dogs
3 Selwyn                Registered dogs — Total registered dogs
4 Selwyn                Registered dogs — Total registered dogs
5 Selwyn                Registered dogs — Total registered dogs
6 Selwyn                Registered dogs — Total registered dogs
  Category                  Value Date DateLabel
1 Beagle                       81 2019 Year ended June
2 All pure and cross breeds 13972 2019 Year ended June
3 All pure breeds            9526 2019 Year ended June
4 Bichon Frise                189 2019 Year ended June
5 Boxer                       160 2019 Year ended June
6 Brazilian Fila                0 2019 Year ended June

  Territorial Authority Measure                     Category
1 Selwyn                Registered dogs — Male dogs All pure and cross breeds
2 Selwyn                Registered dogs — Male dogs All pure breeds
3 Selwyn                Registered dogs — Male dogs Beagle
4 Selwyn                Registered dogs — Male dogs Bichon Frise
5 Selwyn                Registered dogs — Male dogs Boxer
6 Selwyn                Registered dogs — Male dogs Brazilian Fila
  Value Date DateLabel
1 7171  2019 Year ended June
2 4908  2019 Year ended June
3   43  2019 Year ended June
4  114  2019 Year ended June
5   85  2019 Year ended June
6    0  2019 Year ended June

  Territorial Authority Measure                       Category
1 Selwyn                Registered dogs — Female dogs Beagle
2 Selwyn                Registered dogs — Female dogs All pure and cross breeds
3 Selwyn                Registered dogs — Female dogs All pure breeds
4 Selwyn                Registered dogs — Female dogs Bichon Frise
5 Selwyn                Registered dogs — Female dogs Boxer
6 Selwyn                Registered dogs — Female dogs Brazilian Fila
  Value Date DateLabel
1   38  2019 Year ended June
2 6801  2019 Year ended June
3 4618  2019 Year ended June
4   75  2019 Year ended June
5   75  2019 Year ended June
6    0  2019 Year ended June

  Territorial Authority Measure
1 Selwyn                Registered dogs — Micro-chipped dogs
2 Selwyn                Registered dogs — Micro-chipped dogs
3 Selwyn                Registered dogs — Micro-chipped dogs
4 Selwyn                Registered dogs — Micro-chipped dogs
5 Selwyn                Registered dogs — Micro-chipped dogs
6 Selwyn                Registered dogs — Micro-chipped dogs
  Category                  Value Date DateLabel
1 All pure and cross breeds 11172 2019 Year ended June
2 All pure breeds            7390 2019 Year ended June
3 Beagle                       74 2019 Year ended June
4 Bichon Frise                159 2019 Year ended June
5 Boxer                       147 2019 Year ended June
6 Brazilian Fila                0 2019 Year ended June