# Timaru

In [1]:
library(tidyr)
library(tidyverse)
library(readr)
library(skimr)
library(readxl)
library(read_excel)
library(tidyxl)
library(hablar)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──

✔ ggplot2 3.3.2     ✔ dplyr   1.0.2
✔ tibble  3.0.3     ✔ stringr 1.4.0
✔ readr   1.3.1     ✔ forcats 0.5.0
✔ purrr   0.3.4

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

ERROR: Error in library(skimr): there is no package called ‘skimr’

In [2]:
setwd("~/Documents/Uni/DATA422/Group_Project/Pet_CSV")

In [3]:
data = read_csv("Timaru.csv")
pets_data = data[data$Topic == "Pets",]
pets_data
pets_data$Topic = NULL
pets_data$NullReason = NULL
pets_data$Source = NULL
pets_data$ValueUnit = NULL
pets_data$ValueLabel = NULL
skim(pets_data)
pets_data

Parsed with column specification:
cols(
  `Territorial Authority` = col_character(),
  Topic = col_character(),
  Measure = col_character(),
  Category = col_character(),
  Value = col_double(),
  ValueUnit = col_character(),
  ValueLabel = col_character(),
  NullReason = col_character(),
  Date = col_character(),
  DateLabel = col_character(),
  Source = col_character()
)

    Territorial Authority Topic Measure
1   Timaru                Pets  ACC Statistics — Dog-related injury
2   Timaru                Pets  ACC Statistics — Dog-related injury
3   Timaru                Pets  ACC Statistics — Dog-related injury
4   Timaru                Pets  Registered dogs — De-sexed dogs
5   Timaru                Pets  Registered dogs — De-sexed dogs
6   Timaru                Pets  Registered dogs — De-sexed dogs
7   Timaru                Pets  Registered dogs — De-sexed dogs
8   Timaru                Pets  Registered dogs — De-sexed dogs
9   Timaru                Pets  Registered dogs — De-sexed dogs
10  Timaru                Pets  Registered dogs — De-sexed dogs
11  Timaru                Pets  Registered dogs — De-sexed dogs
12  Timaru                Pets  Registered dogs — De-sexed dogs
13  Timaru                Pets  Registered dogs — De-sexed dogs
14  Timaru                Pets  Registered dogs — De-sexed dogs
15  Timaru                Pets  Registered dogs — De-sexed dogs
16  Timaru                Pets  Registered dogs — De-sexed dogs
17  Timaru                Pets  Registered dogs — De-sexed dogs
18  Timaru                Pets  Registered dogs — De-sexed dogs
19  Timaru                Pets  Registered dogs — De-sexed dogs
20  Timaru                Pets  Registered dogs — De-sexed dogs
21  Timaru                Pets  Registered dogs — De-sexed dogs
22  Timaru                Pets  Registered dogs — De-sexed dogs
23  Timaru                Pets  Registered dogs — De-sexed dogs
24  Timaru                Pets  Registered dogs — De-sexed dogs
25  Timaru                Pets  Registered dogs — De-sexed dogs
26  Timaru                Pets  Registered dogs — De-sexed dogs
27  Timaru                Pets  Registered dogs — De-sexed dogs
28  Timaru                Pets  Registered dogs — De-sexed dogs
29  Timaru                Pets  Registered dogs — De-sexed dogs
30  Timaru                Pets  Registered dogs — De-sexed dogs
⋮   ⋮                     ⋮     ⋮
240 Timaru                Pets  Registered dogs — Total registered dogs
241 Timaru                Pets  Registered dogs — Total registered dogs
242 Timaru                Pets  Registered dogs — Total registered dogs
243 Timaru                Pets  Registered dogs — Total registered dogs
244 Timaru                Pets  Registered dogs — Total registered dogs
245 Timaru                Pets  Registered dogs — Total registered dogs
246 Timaru                Pets  Registered dogs — Total registered dogs
247 Timaru                Pets  Registered dogs — Total registered dogs
248 Timaru                Pets  Registered dogs — Total registered dogs
249 Timaru                Pets  Registered dogs — Total registered dogs
250 Timaru                Pets  Registered dogs — Total registered dogs
251 Timaru                Pets  Registered dogs — Total registered dogs
252 Timaru                Pets  Registered dogs — Total registered dogs
253 Timaru                Pets  Registered dogs — Total registered dogs
254 Timaru                Pets  Registered dogs — Total registered dogs
255 Timaru                Pets  Registered dogs — Total registered dogs
256 Timaru                Pets  Registered dogs — Total registered dogs
257 Timaru                Pets  Registered dogs — Total registered dogs
258 Timaru                Pets  Registered dogs — Total registered dogs
259 Timaru                Pets  Registered dogs — Total registered dogs
260 Timaru                Pets  Registered dogs — Total registered dogs
261 Timaru                Pets  Registered dogs — Total registered dogs
262 Timaru                Pets  Registered dogs — Total registered dogs
263 Timaru                Pets  Registered dogs — Total registered dogs
264 Timaru                Pets  Registered dogs — Total registered dogs
265 Timaru                Pets  Registered dogs — Total registered dogs
266 Timaru                Pets  Registered dogs — Total registered dogs
267 Timaru                Pets  Registered dogs — Total registered dogs
268 Timaru                Pets  Registered dogs — Total registered dogs
269 Timaru                Pets  Registered dogs — Total registered dogs
    Category
1   New claims
2   Cost of claims for dog-related injuries received in year (excl. GST)
3   Total cost of claims for all dog-related injuries ever received, up until date (excl. GST)
4   All pure and cross breeds
5   All pure breeds
6   Beagle
7   Bichon Frise
8   Boxer
9   Brazilian Fila
10  Cattle, Australian
11  Chihuahua, Long Coat
12  Chihuahua, Smooth Coat
13  Collie, Bearded
14  Collie, Border
15  Collie, Rough
16  Collie, Smooth
17  Dogo Argentino
18  Greyhound
19  Heading
20  Huntaway
21  Maltese
22  Perro de Presa Canario
23  Poodle, Miniature
24  Poodle, Toy
25  Retriever, Golden
26  Retriever, Labrador
27  Rottweiler
28  Schnauzer, Miniature
29  Shepherd, German
30  Shih Tzu
⋮   ⋮
240 Chihuahua, Smooth Coat
241 Collie, Bearded
242 Collie, Border
243 Collie, Rough
244 Collie, Smooth
245 Dogo Argentino
246 Greyhound
247 Heading
248 Huntaway
249 Maltese
250 Perro de Presa Canario
251 Poodle, Miniature
252 Poodle, Toy
253 Retriever, Golden
254 Retriever, Labrador
255 Rottweiler
256 Schnauzer, Miniature
257 Shepherd, German
258 Shih Tzu
259 Spaniel, Cavalier King Charles
260 Spaniel, Cocker
261 Spaniel, English Springer
262 Terrier, American Pit Bull
263 Terrier, Fox (Smooth)
264 Terrier, Jack Russell
265 Terrier, Staffordshire Bull
266 Terrier, West Highland White
267 Tosa, Japanese
268 Other pure breeds
269 All cross breeds
    Value    ValueUnit ValueLabel           NullReason Date DateLabel
1     129.00 number    Number of new claims NA         2018 Year ended June
2   17867.37 nzd       NZD                  NA         2018 Year ended June
3   19897.44 nzd       NZD                  NA         2018 Year ended June
4    4787.00 number    Number of dogs       NA         2019 Year ended June
5    2928.00 number    Number of dogs       NA         2019 Year ended June
6      29.00 number    Number of dogs       NA         2019 Year ended June
7     131.00 number    Number of dogs       NA         2019 Year ended June
8      43.00 number    Number of dogs       NA         2019 Year ended June
9       0.00 number    Number of dogs       NA         2019 Year ended June
10     15.00 number    Number of dogs       NA         2019 Year ended June
11     46.00 number    Number of dogs       NA         2019 Year ended June
12     33.00 number    Number of dogs       NA         2019 Year ended June
13     18.00 number    Number of dogs       NA         2019 Year ended June
14    157.00 number    Number of dogs       NA         2019 Year ended June
15     10.00 number    Number of dogs       NA         2019 Year ended June
16     14.00 number    Number of dogs       NA         2019 Year ended June
17      0.00 number    Number of dogs       NA         2019 Year ended June
18     25.00 number    Number of dogs       NA         2019 Year ended June
19      6.00 number    Number of dogs       NA         2019 Year ended June
20     44.00 number    Number of dogs       NA         2019 Year ended June
21     71.00 number    Number of dogs       NA         2019 Year ended June
22      0.00 number    Number of dogs       NA         2019 Year ended June
23     25.00 number    Number of dogs       NA         2019 Year ended June
24     32.00 number    Number of dogs       NA         2019 Year ended June
25     87.00 number    Number of dogs       NA         2019 Year ended June
26    400.00 number    Number of dogs       NA         2019 Year ended June
27     62.00 number    Number of dogs       NA         2019 Year ended June
28    124.00 number    Number of dogs       NA         2019 Year ended June
29     93.00 number    Number of dogs       NA         2019 Year ended June
30     37.00 number    Number of dogs       NA         2019 Year ended June
⋮   ⋮        ⋮         ⋮                    ⋮          ⋮    ⋮
240   49     number    Number of dogs       NA         2019 Year ended June
241   61     number    Number of dogs       NA         2019 Year ended June
242  433     number    Number of dogs       NA         2019 Year ended June
243   46     number    Number of dogs       NA         2019 Year ended June
244  355     number    Number of dogs       NA         2019 Year ended June
245    0     number    Number of dogs       NA         2019 Year ended June
246   34     number    Number of dogs       NA         2019 Year ended June
247  149     number    Number of dogs       NA         2019 Year ended June
248  354     number    Number of dogs       NA         2019 Year ended June
249  103     number    Number of dogs       NA         2019 Year ended June
250    0     number    Number of dogs       NA         2019 Year ended June
251   35     number    Number of dogs       NA         2019 Year ended June
252   58     number    Number of dogs       NA         2019 Year ended June
253  169     number    Number of dogs       NA         2019 Year ended June
254  757     number    Number of dogs       NA         2019 Year ended June
255  138     number    Number of dogs       NA         2019 Year ended June
256  164     number    Number of dogs       NA         2019 Year ended June
257  209     number    Number of dogs       NA         2019 Year ended June
258   65     number    Number of dogs       NA         2019 Year ended June
259   36     number    Number of dogs       NA         2019 Year ended June
260  129     number    Number of dogs       NA         2019 Year ended June
261  103     number    Number of dogs       NA         2019 Year ended June
262    7     number    Number of dogs       NA         2019 Year ended June
263  202     number    Number of dogs       NA         2019 Year ended June
264  429     number    Number of dogs       NA         2019 Year ended June
265  197     number    Number of dogs       NA         2019 Year ended June
266   92     number    Number of dogs       NA         2019 Year ended June
267    0     number    Number of dogs       NA         2019 Year ended June
268 1363     number    Number of dogs       NA         2019 Year ended June
269 2790     number    Number of dogs       NA         2019 Year ended June
    Source
1   https://figure.nz/table/fK7iZAOJhHHirYPk
2   https://figure.nz/table/fK7iZAOJhHHirYPk
3   https://figure.nz/table/fK7iZAOJhHHirYPk
4   https://figure.nz/table/fK7iZAOJhHHirYPk
5   https://figure.nz/table/fK7iZAOJhHHirYPk
6   https://figure.nz/table/fK7iZAOJhHHirYPk
7   https://figure.nz/table/fK7iZAOJhHHirYPk
8   https://figure.nz/table/fK7iZAOJhHHirYPk
9   https://figure.nz/table/fK7iZAOJhHHirYPk
10  https://figure.nz/table/fK7iZAOJhHHirYPk
11  https://figure.nz/table/fK7iZAOJhHHirYPk
12  https://figure.nz/table/fK7iZAOJhHHirYPk
13  https://figure.nz/table/fK7iZAOJhHHirYPk
14  https://figure.nz/table/fK7iZAOJhHHirYPk
15  https://figure.nz/table/fK7iZAOJhHHirYPk
16  https://figure.nz/table/fK7iZAOJhHHirYPk
17  https://figure.nz/table/fK7iZAOJhHHirYPk
18  https://figure.nz/table/fK7iZAOJhHHirYPk
19  https://figure.nz/table/fK7iZAOJhHHirYPk
20  https://figure.nz/table/fK7iZAOJhHHirYPk
21  https://figure.nz/table/fK7iZAOJhHHirYPk
22  https://figure.nz/table/fK7iZAOJhHHirYPk
23  https://figure.nz/table/fK7iZAOJhHHirYPk
24  https://figure.nz/table/fK7iZAOJhHHirYPk
25  https://figure.nz/table/fK7iZAOJhHHirYPk
26  https://figure.nz/table/fK7iZAOJhHHirYPk
27  https://figure.nz/table/fK7iZAOJhHHirYPk
28  https://figure.nz/table/fK7iZAOJhHHirYPk
29  https://figure.nz/table/fK7iZAOJhHHirYPk
30  https://figure.nz/table/fK7iZAOJhHHirYPk
⋮   ⋮
240 https://figure.nz/table/fK7iZAOJhHHirYPk
241 https://figure.nz/table/fK7iZAOJhHHirYPk
242 https://figure.nz/table/fK7iZAOJhHHirYPk
243 https://figure.nz/table/fK7iZAOJhHHirYPk
244 https://figure.nz/table/fK7iZAOJhHHirYPk
245 https://figure.nz/table/fK7iZAOJhHHirYPk
246 https://figure.nz/table/fK7iZAOJhHHirYPk
247 https://figure.nz/table/fK7iZAOJhHHirYPk
248 https://figure.nz/table/fK7iZAOJhHHirYPk
249 https://figure.nz/table/fK7iZAOJhHHirYPk
250 https://figure.nz/table/fK7iZAOJhHHirYPk
251 https://figure.nz/table/fK7iZAOJhHHirYPk
252 https://figure.nz/table/fK7iZAOJhHHirYPk
253 https://figure.nz/table/fK7iZAOJhHHirYPk
254 https://figure.nz/table/fK7iZAOJhHHirYPk
255 https://figure.nz/table/fK7iZAOJhHHirYPk
256 https://figure.nz/table/fK7iZAOJhHHirYPk
257 https://figure.nz/table/fK7iZAOJhHHirYPk
258 https://figure.nz/table/fK7iZAOJhHHirYPk
259 https://figure.nz/table/fK7iZAOJhHHirYPk
260 https://figure.nz/table/fK7iZAOJhHHirYPk
261 https://figure.nz/table/fK7iZAOJhHHirYPk
262 https://figure.nz/table/fK7iZAOJhHHirYPk
263 https://figure.nz/table/fK7iZAOJhHHirYPk
264 https://figure.nz/table/fK7iZAOJhHHirYPk
265 https://figure.nz/table/fK7iZAOJhHHirYPk
266 https://figure.nz/table/fK7iZAOJhHHirYPk
267 https://figure.nz/table/fK7iZAOJhHHirYPk
268 https://figure.nz/table/fK7iZAOJhHHirYPk
269 https://figure.nz/table/fK7iZAOJhHHirYPk

ERROR: Error in skim(pets_data): could not find function "skim"

In [4]:
#extract the rows pertaining to ACC information 
acc_pets = pets_data[1:3,]
acc_pets

  Territorial Authority Measure
1 Timaru                ACC Statistics — Dog-related injury
2 Timaru                ACC Statistics — Dog-related injury
3 Timaru                ACC Statistics — Dog-related injury
  Category
1 New claims
2 Cost of claims for dog-related injuries received in year (excl. GST)
3 Total cost of claims for all dog-related injuries ever received, up until date (excl. GST)
  Value    Date DateLabel
1   129.00 2018 Year ended June
2 17867.37 2018 Year ended June
3 19897.44 2018 Year ended June

In [5]:
#Then we can extract the rows pertaining to specific counts of dogs 
pets_counts = pets_data[c(-1,-2,-3),]
pets_counts

    Territorial Authority Measure
1   Timaru                Registered dogs — De-sexed dogs
2   Timaru                Registered dogs — De-sexed dogs
3   Timaru                Registered dogs — De-sexed dogs
4   Timaru                Registered dogs — De-sexed dogs
5   Timaru                Registered dogs — De-sexed dogs
6   Timaru                Registered dogs — De-sexed dogs
7   Timaru                Registered dogs — De-sexed dogs
8   Timaru                Registered dogs — De-sexed dogs
9   Timaru                Registered dogs — De-sexed dogs
10  Timaru                Registered dogs — De-sexed dogs
11  Timaru                Registered dogs — De-sexed dogs
12  Timaru                Registered dogs — De-sexed dogs
13  Timaru                Registered dogs — De-sexed dogs
14  Timaru                Registered dogs — De-sexed dogs
15  Timaru                Registered dogs — De-sexed dogs
16  Timaru                Registered dogs — De-sexed dogs
17  Timaru                Registered dogs — De-sexed dogs
18  Timaru                Registered dogs — De-sexed dogs
19  Timaru                Registered dogs — De-sexed dogs
20  Timaru                Registered dogs — De-sexed dogs
21  Timaru                Registered dogs — De-sexed dogs
22  Timaru                Registered dogs — De-sexed dogs
23  Timaru                Registered dogs — De-sexed dogs
24  Timaru                Registered dogs — De-sexed dogs
25  Timaru                Registered dogs — De-sexed dogs
26  Timaru                Registered dogs — De-sexed dogs
27  Timaru                Registered dogs — De-sexed dogs
28  Timaru                Registered dogs — De-sexed dogs
29  Timaru                Registered dogs — De-sexed dogs
30  Timaru                Registered dogs — De-sexed dogs
⋮   ⋮                     ⋮
237 Timaru                Registered dogs — Total registered dogs
238 Timaru                Registered dogs — Total registered dogs
239 Timaru                Registered dogs — Total registered dogs
240 Timaru                Registered dogs — Total registered dogs
241 Timaru                Registered dogs — Total registered dogs
242 Timaru                Registered dogs — Total registered dogs
243 Timaru                Registered dogs — Total registered dogs
244 Timaru                Registered dogs — Total registered dogs
245 Timaru                Registered dogs — Total registered dogs
246 Timaru                Registered dogs — Total registered dogs
247 Timaru                Registered dogs — Total registered dogs
248 Timaru                Registered dogs — Total registered dogs
249 Timaru                Registered dogs — Total registered dogs
250 Timaru                Registered dogs — Total registered dogs
251 Timaru                Registered dogs — Total registered dogs
252 Timaru                Registered dogs — Total registered dogs
253 Timaru                Registered dogs — Total registered dogs
254 Timaru                Registered dogs — Total registered dogs
255 Timaru                Registered dogs — Total registered dogs
256 Timaru                Registered dogs — Total registered dogs
257 Timaru                Registered dogs — Total registered dogs
258 Timaru                Registered dogs — Total registered dogs
259 Timaru                Registered dogs — Total registered dogs
260 Timaru                Registered dogs — Total registered dogs
261 Timaru                Registered dogs — Total registered dogs
262 Timaru                Registered dogs — Total registered dogs
263 Timaru                Registered dogs — Total registered dogs
264 Timaru                Registered dogs — Total registered dogs
265 Timaru                Registered dogs — Total registered dogs
266 Timaru                Registered dogs — Total registered dogs
    Category                       Value Date DateLabel
1   All pure and cross breeds      4787  2019 Year ended June
2   All pure breeds                2928  2019 Year ended June
3   Beagle                           29  2019 Year ended June
4   Bichon Frise                    131  2019 Year ended June
5   Boxer                            43  2019 Year ended June
6   Brazilian Fila                    0  2019 Year ended June
7   Cattle, Australian               15  2019 Year ended June
8   Chihuahua, Long Coat             46  2019 Year ended June
9   Chihuahua, Smooth Coat           33  2019 Year ended June
10  Collie, Bearded                  18  2019 Year ended June
11  Collie, Border                  157  2019 Year ended June
12  Collie, Rough                    10  2019 Year ended June
13  Collie, Smooth                   14  2019 Year ended June
14  Dogo Argentino                    0  2019 Year ended June
15  Greyhound                        25  2019 Year ended June
16  Heading                           6  2019 Year ended June
17  Huntaway                         44  2019 Year ended June
18  Maltese                          71  2019 Year ended June
19  Perro de Presa Canario            0  2019 Year ended June
20  Poodle, Miniature                25  2019 Year ended June
21  Poodle, Toy                      32  2019 Year ended June
22  Retriever, Golden                87  2019 Year ended June
23  Retriever, Labrador             400  2019 Year ended June
24  Rottweiler                       62  2019 Year ended June
25  Schnauzer, Miniature            124  2019 Year ended June
26  Shepherd, German                 93  2019 Year ended June
27  Shih Tzu                         37  2019 Year ended June
28  Spaniel, Cavalier King Charles   30  2019 Year ended June
29  Spaniel, Cocker                  76  2019 Year ended June
30  Spaniel, English Springer        40  2019 Year ended June
⋮   ⋮                              ⋮     ⋮    ⋮
237 Chihuahua, Smooth Coat           49  2019 Year ended June
238 Collie, Bearded                  61  2019 Year ended June
239 Collie, Border                  433  2019 Year ended June
240 Collie, Rough                    46  2019 Year ended June
241 Collie, Smooth                  355  2019 Year ended June
242 Dogo Argentino                    0  2019 Year ended June
243 Greyhound                        34  2019 Year ended June
244 Heading                         149  2019 Year ended June
245 Huntaway                        354  2019 Year ended June
246 Maltese                         103  2019 Year ended June
247 Perro de Presa Canario            0  2019 Year ended June
248 Poodle, Miniature                35  2019 Year ended June
249 Poodle, Toy                      58  2019 Year ended June
250 Retriever, Golden               169  2019 Year ended June
251 Retriever, Labrador             757  2019 Year ended June
252 Rottweiler                      138  2019 Year ended June
253 Schnauzer, Miniature            164  2019 Year ended June
254 Shepherd, German                209  2019 Year ended June
255 Shih Tzu                         65  2019 Year ended June
256 Spaniel, Cavalier King Charles   36  2019 Year ended June
257 Spaniel, Cocker                 129  2019 Year ended June
258 Spaniel, English Springer       103  2019 Year ended June
259 Terrier, American Pit Bull        7  2019 Year ended June
260 Terrier, Fox (Smooth)           202  2019 Year ended June
261 Terrier, Jack Russell           429  2019 Year ended June
262 Terrier, Staffordshire Bull     197  2019 Year ended June
263 Terrier, West Highland White     92  2019 Year ended June
264 Tosa, Japanese                    0  2019 Year ended June
265 Other pure breeds              1363  2019 Year ended June
266 All cross breeds               2790  2019 Year ended June

In [6]:
#And we can extract rows and make tables therefore of the different measures of dogs they have 
desexed_counts = pets_counts[pets_counts$Measure == "Registered dogs — De-sexed dogs",]
desexed_counts %>%
head()

dangerous_counts = pets_counts[pets_counts$Measure =="Registered dogs — Dogs classified as dangerous",]
dangerous_counts %>%
head()

menacing_counts = pets_counts[pets_counts$Measure =="Registered dogs — Dogs classified as menacing",]
menacing_counts %>%
head()

total_registered_dogs = pets_counts[pets_counts$Measure =="Registered dogs — Total registered dogs",]
total_registered_dogs %>%
head()

male_dogs = pets_counts[pets_counts$Measure =="Registered dogs — Male dogs",]
male_dogs %>%
head()

female_dogs = pets_counts[pets_counts$Measure == "Registered dogs — Female dogs",]
female_dogs %>%
head()

microchipped_dogs = pets_counts[pets_counts$Measure =="Registered dogs — Micro-chipped dogs",]
microchipped_dogs %>%
head()

  Territorial Authority Measure
1 Timaru                Registered dogs — De-sexed dogs
2 Timaru                Registered dogs — De-sexed dogs
3 Timaru                Registered dogs — De-sexed dogs
4 Timaru                Registered dogs — De-sexed dogs
5 Timaru                Registered dogs — De-sexed dogs
6 Timaru                Registered dogs — De-sexed dogs
  Category                  Value Date DateLabel
1 All pure and cross breeds 4787  2019 Year ended June
2 All pure breeds           2928  2019 Year ended June
3 Beagle                      29  2019 Year ended June
4 Bichon Frise               131  2019 Year ended June
5 Boxer                       43  2019 Year ended June
6 Brazilian Fila               0  2019 Year ended June

  Territorial Authority Measure
1 Timaru                Registered dogs — Dogs classified as dangerous
2 Timaru                Registered dogs — Dogs classified as dangerous
3 Timaru                Registered dogs — Dogs classified as dangerous
4 Timaru                Registered dogs — Dogs classified as dangerous
5 Timaru                Registered dogs — Dogs classified as dangerous
6 Timaru                Registered dogs — Dogs classified as dangerous
  Category                  Value Date DateLabel
1 All pure and cross breeds 9     2019 Year ended June
2 All pure breeds           6     2019 Year ended June
3 Beagle                    0     2019 Year ended June
4 Bichon Frise              0     2019 Year ended June
5 Boxer                     0     2019 Year ended June
6 Brazilian Fila            0     2019 Year ended June

  Territorial Authority Measure
1 Timaru                Registered dogs — Dogs classified as menacing
2 Timaru                Registered dogs — Dogs classified as menacing
3 Timaru                Registered dogs — Dogs classified as menacing
4 Timaru                Registered dogs — Dogs classified as menacing
5 Timaru                Registered dogs — Dogs classified as menacing
6 Timaru                Registered dogs — Dogs classified as menacing
  Category                  Value Date DateLabel
1 All pure and cross breeds 77    2019 Year ended June
2 All pure breeds           33    2019 Year ended June
3 Beagle                     0    2019 Year ended June
4 Bichon Frise               0    2019 Year ended June
5 Boxer                      0    2019 Year ended June
6 Brazilian Fila             0    2019 Year ended June

  Territorial Authority Measure
1 Timaru                Registered dogs — Total registered dogs
2 Timaru                Registered dogs — Total registered dogs
3 Timaru                Registered dogs — Total registered dogs
4 Timaru                Registered dogs — Total registered dogs
5 Timaru                Registered dogs — Total registered dogs
6 Timaru                Registered dogs — Total registered dogs
  Category                  Value Date DateLabel
1 All pure and cross breeds 8926  2019 Year ended June
2 All pure breeds           6136  2019 Year ended June
3 Beagle                      41  2019 Year ended June
4 Bichon Frise               183  2019 Year ended June
5 Boxer                       69  2019 Year ended June
6 Brazilian Fila               0  2019 Year ended June

  Territorial Authority Measure                     Category
1 Timaru                Registered dogs — Male dogs All pure and cross breeds
2 Timaru                Registered dogs — Male dogs All pure breeds
3 Timaru                Registered dogs — Male dogs Beagle
4 Timaru                Registered dogs — Male dogs Bichon Frise
5 Timaru                Registered dogs — Male dogs Boxer
6 Timaru                Registered dogs — Male dogs Brazilian Fila
  Value Date DateLabel
1 4444  2019 Year ended June
2 3065  2019 Year ended June
3   17  2019 Year ended June
4  107  2019 Year ended June
5   31  2019 Year ended June
6    0  2019 Year ended June

  Territorial Authority Measure                       Category
1 Timaru                Registered dogs — Female dogs Brazilian Fila
2 Timaru                Registered dogs — Female dogs All pure and cross breeds
3 Timaru                Registered dogs — Female dogs All pure breeds
4 Timaru                Registered dogs — Female dogs Beagle
5 Timaru                Registered dogs — Female dogs Bichon Frise
6 Timaru                Registered dogs — Female dogs Boxer
  Value Date DateLabel
1    0  2019 Year ended June
2 4482  2019 Year ended June
3 3071  2019 Year ended June
4   24  2019 Year ended June
5   76  2019 Year ended June
6   38  2019 Year ended June

  Territorial Authority Measure
1 Timaru                Registered dogs — Micro-chipped dogs
2 Timaru                Registered dogs — Micro-chipped dogs
3 Timaru                Registered dogs — Micro-chipped dogs
4 Timaru                Registered dogs — Micro-chipped dogs
5 Timaru                Registered dogs — Micro-chipped dogs
6 Timaru                Registered dogs — Micro-chipped dogs
  Category                  Value Date DateLabel
1 All pure and cross breeds 6755  2019 Year ended June
2 All pure breeds           4419  2019 Year ended June
3 Beagle                      39  2019 Year ended June
4 Bichon Frise               151  2019 Year ended June
5 Boxer                       57  2019 Year ended June
6 Brazilian Fila               0  2019 Year ended June